# Numpy

import

In [1]:
import numpy as np

cast normal list to np array

In [3]:
l = [1, 2, 3]

np_l = np.array(l)
print(np_l, type(np_l))

[1 2 3] <class 'numpy.ndarray'>


size of list

In [4]:
np_l.size

3

In [5]:
np_l.shape

(3,)

In [6]:
np_l * 2

array([2, 4, 6])

In [7]:
np.zeros((2,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
np.arange(12).reshape(4,3) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
list_a = np.array([1, 2, 3, 4])
list_b = np.array([4, 3, 5, 10])
list_c = list_b - list_a
list_c

array([3, 1, 2, 6])

In [11]:
list_a.dot(list_b)

65

also supports sum etc

In [12]:
list_c.sum()

12

In [14]:
list_c.mean()

3.0